### ISSUE TITLE
b0rken with next HASS

### ISSUE THREAD

**Issue by lolorc** [elric91/homeassistant_zigate#26]
hi,

just to let you know, it looks like your plugin will be broken by next HASS update 0.69

**Comment by elric91** [comment]
Did you experienced it or did you see anything in the coming release note ?

**Comment by lolorc** [comment]
sorry I should have given the stacktrace, yes I experienced it and I reverted to the latest stable, hence me not giving more detail.

**Comment by lolorc** [comment]
my mistake, looks ok with 0.69.1, it's with dev (next 0.70) that it looks broken

**Comment by max5962** [comment]
@lolorc  it's still broken in the last version of HASS ( 0.71 ?)

**Comment by max5962** [comment]
![image](https://user-images.githubusercontent.com/34659571/41908717-3dfe2e74-7945-11e8-9409-368fb4a88a47.png)
No issues with the latests

**Comment by ruimarinho** [comment]
I've experienced the same issue as well — trouble with 0.70.0+ but now working fine with 0.72.1 again.

**Comment by pdecat** [comment]
Apparently, the issue is happening when try to load a complete configuration (with `zigate:` *and* `platform: zigate` light, sensor or switch items) on a clean install of home assistant where `pyzigate` package is not already installed:

```
2018-06-27 07:10:53 ERROR (SyncWorker_1) [homeassistant.loader] Unable to find component light.zigate                                                                                                                                                                                                                
2018-06-27 07:10:53 ERROR (SyncWorker_1) [homeassistant.loader] Error loading custom_components.light.zigate. Make sure all dependencies are installed                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                                                                   
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 86, in get_component                                                                                                                                                                                                                         
    module = importlib.import_module(path)                                                                                                                                                                                                                                                     
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module                                                                                                                                                                                                                                        
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                                                                                                                      
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                                                                                                                                                                                                                                     
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                                                                                                                                                                                                                  
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                                                                                                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                                                                                                                                                                                                                  
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                                                                                                                                                                                                                           
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                                                                                                           
  File "/config/custom_components/light/zigate.py", line 17, in <module>                                                                                                                                                                                                                              
    from pyzigate.zgt_parameters import *                                                                                                                                                                                                                                                                            
ModuleNotFoundError: No module named 'pyzigate'                                                                                                                                                                                                                                                                      
```

Checking configuration then fails with:

```
2018-06-27 07:17:07 ERROR (MainThread) [homeassistant.components.hassio] Testing configuration at /config
Failed config
  General Errors:
    - Platform not found: switch.zigate
    - Platform not found: switch.zigate
    - Platform not found: light.zigate
    - Platform not found: light.zigate
    - Platform not found: light.zigate
    - Platform not found: light.zigate

Successful config (partial)
```

Workaround is to comment all but `zigate:` configuration, restart and let HA install the dependencies, uncomment, then restart again.

Looks like its a matter of missing dependencies and requirements in the light, sensor and switch components:

```
DEPENDENCIES = ['zigate']
REQUIREMENTS = ['pyzigate==0.1.3.post1']
```

**Comment by ISO-B** [comment]
Tested with HASS 0.82.1 without pyzigate installed no errors.
